version: '3.9'
services:
  postgres:
    container_name: challenge-db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: challenge-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
  review-service:
    container_name: review-service
    image: review_service
    pull_policy: missing
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - "8081:8080"
  product-service:
    container_name: product-service
    image: product_service
    pull_policy: missing
    depends_on:
      - postgres
      - review-service
    restart: unless-stopped
    ports:
      - "8082:8080"
